function nfigloglog(X1, Y1, YNeg1, YPos1,caso)
%CREATEFIGURE(X1, Y1, YNeg1, YPos1)
%  X1:  errorbar x vector data
%  Y1:  errorbar y vector data
%  YNEG1:  errorbar ynegativedelta vector data
%  YPOS1:  errorbar ypositivedelta vector data

%  Auto-generated by MATLAB on 02-Sep-2019 20:55:42

% Create axes
axes1 = axes('Parent');
hold(axes1,'on');

% Create errorbar
errorbar(X1,Y1,YNeg1,YPos1);

% Create ylabel
ylabel('n(r), Numero de cajas');

% Create xlabel
xlabel('r, Tamaño de caja');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1 1000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.8 1000]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XMinorTick','on','XScale','log','YMinorTick','on','YScale','log');
