function [BW,maskedImage] = segTarget(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 12-Sep-2019
%----------------------------------------------------


% Graph cut
foregroundInd = [65 66 67 ];
backgroundInd = [1 2 3 4 101 102 103 104 ];
L = superpixels(X,101);
BW = lazysnapping(X,L,foregroundInd,backgroundInd);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

