function [BW,maskedImage] = segtImgDrop(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 12-Sep-2019
%----------------------------------------------------



% Find circles
[centers,radii,~] = imfindcircles(X,[7 13],'ObjectPolarity','dark','Sensitivity',0.99);
BW = false(size(X,1),size(X,2));
[Xgrid,Ygrid] = meshgrid(1:size(BW,2),1:size(BW,1));
BW = BW | (hypot(Xgrid-centers(1,1),Ygrid-centers(1,2)) <= radii(1));

% imshow(BW)
% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

