function [BW,maskedImage] = segTarget(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 12-Sep-2019
%----------------------------------------------------


% Graph cut
foregroundInd = [33 34 35 36 37 40 41 44 45 48 49 52 53 56 57 60 61 64 65 66 67 68 ];
backgroundInd = [1 2 3 4 5 8 9 10 11 12 85 86 87 88 89 92 93 96 97 100 101 102 103 104 ];
L = superpixels(X,101);
BW = lazysnapping(X,L,foregroundInd,backgroundInd);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

